# Generated by Django 5.1.6 on 2025-03-22 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('low', 'Низкий'), ('moderate', 'Умеренный'), ('high', 'Высокий')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='allergy',
            field=models.ManyToManyField(blank=True, related_name='allergies', to='menu.recipe'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='goal',
            field=models.CharField(blank=True, choices=[('mass_gain', 'Набор массы'), ('weight_loss', 'Сброс веса'), ('weight_maintenance', 'Поддержание веса')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CalorieCalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('calorie_need', models.PositiveIntegerField()),
                ('goal', models.CharField(choices=[('mass_gain', 'Набор массы'), ('weight_loss', 'Сброс веса'), ('weight_maintenance', 'Поддержание веса')], max_length=50)),
                ('activity_level', models.CharField(choices=[('low', 'Низкий'), ('moderate', 'Умеренный'), ('high', 'Высокий')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSelectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('selected_menu', models.TextField()),
                ('calorie_count', models.PositiveIntegerField()),
                ('activity_level', models.CharField(choices=[('low', 'Низкий'), ('moderate', 'Умеренный'), ('high', 'Высокий')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
