# Generated by Django 5.1.6 on 2025-03-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_activity_level_customuser_allergy_and_more'),
        ('calorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='allergy',
            field=models.ManyToManyField(blank=True, related_name='allergies', to='calorie.product'),
        ),
    ]
