# Generated by Django 5.1.6 on 2025-03-22 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_savedmenu_delete_menuselectionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSelectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('selected_menu', models.TextField()),
                ('calorie_count', models.PositiveIntegerField()),
                ('activity_level', models.CharField(choices=[('low', 'Низкий'), ('moderate', 'Умеренный'), ('high', 'Высокий')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SavedMenu',
        ),
    ]
