# Generated by Django 5.1.6 on 2025-03-22 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_menuselectionhistory_delete_savedmenu'),
        ('menu', '0002_recipe_is_vegan_recipe_meal_type_recipe_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipes', models.ManyToManyField(to='menu.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_menus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MenuSelectionHistory',
        ),
    ]
