# Generated by Django 5.1.6 on 2025-03-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_savedmenu_delete_menuselectionhistory'),
        ('calorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='calorie.product'),
        ),
    ]
